apiVersion: v1
kind: Service
metadata:
  name: {{ include "strapi.fullname" . }}
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "strapi.selectorLabels" . | nindent 4 }}


#metadata:
#  name: {{ template "strapi.fullname" . }}
#  labels:
#    app: {{ template "strapi.name" . }}
#    chart: {{ template "strapi.chart" . }}
#    release: {{ .Release.Name }}
#    heritage: {{ .Release.Service }}