# Default values for strapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

envs:
  - name: APPLICATION_NAME
    value: "strapi"
  - name: PORT
    value: '1337'
  - name: NODE_ENV
    value: development
  - name: DATABASE_HOST
    value: mongodb://{ Change to your mongo service }:27017/strapi-db?authSource=strapi-db&gssapiServiceName=mongodb
  - name: DATABASE_NAME
    value: "strapi-db"
  - name: DATABASE_SVR
    value: "false"
  - name: DATABASE_PORT
    value: "27017"
  - name: DATABASE_SS1
    value: "false"

image:
  repository: {your registry}
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "strapi"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

liveness:
  enabled: 1
  path: "/healthz"

readiness:
  enabled: 1
  path: "/healthz"

nginx:
  image:
    tag: 1.15-alpine
  config:
    file: nginx.conf
  resources:
    limits:
      cpu: 100m
      memory: 128mi
    requests: 
      cpu: 50m
      memory: 64mi

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kube.privateproperty.cloud
      paths:
        - path: /rundeck
          backend:
            serviceName: rundeck
            servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  cpu:
    enabled: 0
    targetPercentage: 60
  memory:
    enabled: 0
    targetPercentage: 60
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
